server:
  port: 9081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e-rommerce
    username: postgres
    password: root


  data:
    redis:
      host: localhost
      port: 6379

  web:
    locale: en_EN
    locale-resolver: fixed

  jpa:
    hibernate:
      ddl-auto: validate

  authentication:
    unauthorized-message: "UNAUTHORIZED"
